### ISSUE TITLE
Update for DocPad 6.x

### ISSUE THREAD

**Issue by greduan** [DjebbZ/docpad-plugin-sitemap#5]
@DjebbZ I'd be very interested in using this plugin but it seems it hasn't been updated since the last major release of DocPad.

You think you could update it? :)

**Comment by DjebbZ** [comment]
Hello,
Why do you need an update ? It isn't working now ?

**Comment by greduan** [comment]
That is correct. Also since the dependencies you have set in your plugin are for version 5.x of DocPad it won't be using the latest version of DocPad when regenerating.

Also the structure for the plugin that it's using right now is no longer compatible with the way DocPad handles it now, I believe.

**Comment by DjebbZ** [comment]
I'm stupid, I forgot that the plugin is now curated by Docpad itself, based on my work. Here's the repo : https://github.com/docpad/docpad-plugin-sitemap

**Comment by greduan** [comment]
Oh OK. Excellent, thank you! :)
